# Logger options
log_iter: 10                 # How often to log the training loss 
val_iter: 200                # How often to validate testing and save output images during training

# Optimization options
max_iter: 30000                # Maximum number of training iterations
batch_size: 1             # Batch size
loss: L2
optimizer: Adam               # Optimizer for trainings
weight_decay: 0.01             # Weight decay
beta1: 0.9                    # Adam parameter
beta2: 0.999                  # Adam parameter
lr: 0.00005                    # Initial learning rate [RFF: 10-3, Neural Recon: 10-4, Prior-based Neural Recon: 10-5]


# Model options
model: SIREN                  # Options for MLP models
net: 
  network_input_size: 512     # Input size for network
  network_depth: 8            # Depth of MLP layers
  network_width: 512          # Width of MLP layers

encoder:
  embedding: gauss            # Input embedding method
  scale: 1
  embedding_size: 256         # Embedding size for input Fourier feature encoding
  coordinates_size: 2




# Data
img_size: 192     # (92, 256, 256)
data_folder: ./NERF_data/BraTS_2D/
dataset_name: BraTS